// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnragdvGqdujqAZYWd9q0DOafdImbqb9I',
    appId: '1:460204429854:web:bda1da67a1878bceab940f',
    messagingSenderId: '460204429854',
    projectId: 'dailyglow-54fe1',
    authDomain: 'dailyglow-54fe1.firebaseapp.com',
    storageBucket: 'dailyglow-54fe1.firebasestorage.app',
    measurementId: 'G-6Q4ZBWXFHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzZXmdMwNHEYflHaBoNfHG9Cd9hwCtooQ',
    appId: '1:460204429854:android:a5796e416238f7f1ab940f',
    messagingSenderId: '460204429854',
    projectId: 'dailyglow-54fe1',
    storageBucket: 'dailyglow-54fe1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2fGZMUhKNj8u6idqMrS1ta_yZd6nmqq8',
    appId: '1:460204429854:ios:c818f3d8bf1bfce9ab940f',
    messagingSenderId: '460204429854',
    projectId: 'dailyglow-54fe1',
    storageBucket: 'dailyglow-54fe1.firebasestorage.app',
    iosBundleId: 'com.example.dailyglow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2fGZMUhKNj8u6idqMrS1ta_yZd6nmqq8',
    appId: '1:460204429854:ios:c818f3d8bf1bfce9ab940f',
    messagingSenderId: '460204429854',
    projectId: 'dailyglow-54fe1',
    storageBucket: 'dailyglow-54fe1.firebasestorage.app',
    iosBundleId: 'com.example.dailyglow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnragdvGqdujqAZYWd9q0DOafdImbqb9I',
    appId: '1:460204429854:web:2768ad5397cd3b12ab940f',
    messagingSenderId: '460204429854',
    projectId: 'dailyglow-54fe1',
    authDomain: 'dailyglow-54fe1.firebaseapp.com',
    storageBucket: 'dailyglow-54fe1.firebasestorage.app',
    measurementId: 'G-E4BJCBKDFY',
  );
}
